---
title: "540_validation"
author: "Alice Ziegler"
date: '2022-09-30'
output: html_document
---

## Setup
```{r setup, include=FALSE, echo = F}
rm(list=ls())
#####
### TO DO
#####
#? ich bin nicht sicher ob sd nach Monat so sinnvoll ist  - aber zum Vergleich der Monate untereinander evtl schon...


#####
### load packages & stuff
#####
library(CAST)
library(caret)
library(ranger)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(viridis)
library(data.table)
library(sf)
library(scales)

source("000_R_presettings.R")#different path, due to .Rmd
#####
### general settings
#####
comm_filt <- paste0(comm, "no2022_inclMix_")
# comm_filt <- paste0(comm, "no2022_onlynight")
comm_mod <- paste0(comm_filt, "val_21_total")
# comm_mod <- paste0(comm_filt, "val_21_total_balanced_")
# comm_mod <- paste0(comm_filt, "val_21_total_balanced_150000")
# comm_mod <- paste0(comm_filt, "val_21_total_balanced_150000_props")

cor_val <- c("12" = "lightgoldenrod3","18" = "darkorange", "23" = "darkolivegreen1",
                                 "24" = "springgreen3","25" = "forestgreen") #for values in scale fill manual
cor_lab <- c("arable land", "pasture", "broad leaved", "coniferous", "mixed forest")

```

## Preparation of data
```{r}

#####
### read data
#####
model <- readRDS(file = paste0(out_path, "060_test_model", comm_mod, ".rds"))
train_data <- readRDS(file = paste0(gee_path, "050_data_train", comm_mod, ".rds"))
test_data <- readRDS(file = paste0(gee_path, "050_data_test", comm_mod, ".rds")) # 2021


# !!!delete following with next run
#####
### create additional colums needed ###can be deleted, is newly implemented in 030
#####
#corine als factor
test_data$corine_factor <- as.factor(test_data$corine) ###can be deleted, is newly implemented in 040
train_data$corine_factor <- as.factor(train_data$corine) ###can be deleted, is newly implemented in 040
test_data$NDVI <- test_data$NDVI/10000
train_data$NDVI <- train_data$NDVI/10000

#####
### create general lookups
#####

#unique vectors 
corine_unique <- unique(test_data$corine)[order(unique(test_data$corine))]
month_unique <- unique(test_data$month)[order(unique(test_data$month))]
cor_mon_unique_rnd <- unique(as.data.frame(test_data)[c("corine", "month")])
cor_mon_unique <- cor_mon_unique_rnd[with(cor_mon_unique_rnd, order(month, corine)),]

# obs metrics grouped by corine (obs mean and sd)
corine_aggregate_matrix <- aggregate(pai ~ corine, test_data, function(x) c(mean = mean(x), sd = sd(x)))
corine_aggregate <- do.call("data.frame", corine_aggregate_matrix)
colnames(corine_aggregate)[which(colnames(corine_aggregate) %in% c("pai.mean", "pai.sd"))] <- c("pai_obs_test_mean", "pai_obs_test_sd")

# obs metrics grouped by month 
#? ich bin nicht sicher ob sd nach Monat so sinnvoll ist  - aber zum Vergleich der Monate untereinander evtl schon...
month_aggregate_matrix <- aggregate(pai ~ month, test_data, function(x) c(mean = mean(x), sd = sd(x)))
month_aggregate <- do.call("data.frame", month_aggregate_matrix)
colnames(month_aggregate)[which(colnames(month_aggregate) %in% c("pai.mean", "pai.sd"))] <- c("pai_obs_est_mean", "pai_obs_test_sd")

# obs metrics grouped by month and corine
cor_mon_aggregate_matrix <- aggregate(pai ~ month+corine, test_data, function(x) c(mean = mean(x), sd = sd(x)))
cor_mon_aggregate <- do.call("data.frame", cor_mon_aggregate_matrix)
colnames(cor_mon_aggregate)[which(colnames(cor_mon_aggregate) %in% c("pai.mean", "pai.sd"))] <- c("pai_obs_est_mean", "pai_obs_test_sd")
```

## validation

# predict points of 2021
```{r}
test_data <- data.frame(test_data, pred = predict(model, st_drop_geometry(test_data)))
```

# external error metrics 
```{r}
smmry_data <- data.frame(obs = test_data$pai, pred = test_data$pred)
smmry <- defaultSummary(smmry_data)
smmry <- as.data.frame(t(smmry))
smmry$RMSE_sd_obs <- smmry$RMSE/sd(smmry_data$obs)
write.csv(smmry, paste0(fig_path, "070_error_smmry_external", comm_mod, ".csv"))
```

## frequencies of points by month and corine class (train_data)
```{r}
tbl_cor <- table(as.data.frame(train_data)[,"corine"])
tbl_mon <- table(as.data.frame(train_data)[,"month"])
tbl_n_cor_mon <- table(as.data.frame(train_data)[,c("month", "corine")])
write.csv(tbl_n_cor_mon, paste0(fig_path, "070_n_cor_mon_tbl", comm_mod, ".csv"))

tbl_n_cor_mon_long <- as.data.frame(tbl_n_cor_mon)

n_cor_mon <-
  ggplot(data = tbl_n_cor_mon_long, mapping = aes(x = month, y = corine, fill = Freq)) + 
  geom_tile() + 
  geom_text(aes(label = round(Freq, 2))) +
  scale_fill_viridis(discrete = F) +
  labs(fill = "frequency")+
  xlab(label= "month")+
  theme_bw()+
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())+
  scale_y_discrete(expand=c(0,0), labels = cor_lab)+
  scale_x_discrete(expand=c(0,0))
print(n_cor_mon)
ggsave(filename = paste0(fig_path, "070_n_cor_mon_fig", comm_mod, ".pdf"),
       plot = n_cor_mon,
       width = 200, height = 150, units = "mm", dpi = 300)


###
# ggplot(data = heat_r2, mapping = aes(x = month, y = corine, fill = Rsquared)) + 
#   geom_tile() + 
#   geom_text(aes(label = round(Rsquared, 2))) +
#   scale_fill_viridis(discrete = F) +
#   labs(fill = "R²")+
#   xlab(label= "month")+
#   theme_bw()+
#   theme(panel.border = element_blank(), panel.grid.major = element_blank(),
#         panel.grid.minor = element_blank())+
#   scale_y_discrete(expand=c(0,0), labels = cor_lab)+
#   scale_x_discrete(expand=c(0,0))
###
```


## calculate errors for all and subgroups and prepare data for plotting
```{r}
# errors total model
errors <- defaultSummary(data.frame(obs = test_data$pai, pred = test_data$pred))

# errors by corine group
errors_corine_lst <- lapply(corine_unique, function(i){
  err <- defaultSummary(data.frame(obs = test_data$pai[test_data$corine == i], 
                                   pred = test_data$pred[test_data$corine == i]))
})
errors_corine <- merge(corine_aggregate, data.frame(corine = corine_unique, as.data.frame(do.call("rbind", errors_corine_lst))), by = "corine")
errors_corine$RMSE_sd <- errors_corine$RMSE/errors_corine$pai_obs_test_sd
write.csv(errors_corine, paste0(fig_path, "070_errors_corine_", comm_mod, ".csv"))
#create long table for plot
errors_corine_long <- melt(setDT(errors_corine), id.vars = c("corine"), 
                          variable.name = "error_metric")

# errors by month
errors_month_lst <- lapply(month_unique, function(i){
  err <- defaultSummary(data.frame(obs = test_data$pai[test_data$month == i], 
                                   pred = test_data$pred[test_data$month == i]))
})
errors_month <- merge(month_aggregate, data.frame(month = month_unique, as.data.frame(do.call("rbind", errors_month_lst))), by = "month")
errors_month$RMSE_sd <- errors_month$RMSE/errors_month$pai_obs_test_sd
write.csv(errors_month, paste0(fig_path, "070_errors_month_", comm_mod, ".csv"))
#create long table for plot
errors_month_long <- melt(setDT(errors_month), id.vars = c("month"), 
                          variable.name = "error_metric")

#errors by corine and month
errors_cor_mon_lst <- lapply(seq(nrow(cor_mon_unique)), function(i){
  mon <- cor_mon_unique$month[i]
  cor <- cor_mon_unique$corine[i]
  err <- defaultSummary(data.frame(obs = test_data$pai[test_data$month == mon & test_data$corine == cor], 
                                   pred = test_data$pred[test_data$month == mon & test_data$corine == cor]))
})
errors_cor_mon <- merge(cor_mon_aggregate, data.frame(cor_mon_unique, as.data.frame(do.call("rbind", errors_cor_mon_lst))), by = c("month", "corine"))
errors_cor_mon$RMSE_sd <- errors_cor_mon$RMSE/errors_cor_mon$pai_obs_test_sd

###create table< for heatmap
#wide table
heat_r2 <- errors_cor_mon[,c("month", "corine", "Rsquared")]
heat_r2 <- heat_r2[!duplicated(heat_r2),]
# change corine to factors so there are no gaps for missing classes
heat_r2$corine <- as.factor(heat_r2$corine)
heat_r2_cross <-  reshape(heat_r2, idvar = "corine", timevar = "month", direction = "wide")
write.csv(heat_r2_cross, paste0(fig_path, "070_heat_r2_cross_", comm_mod, ".csv"))

#wide table
heat_rmsesd <- errors_cor_mon[,c("month", "corine", "RMSE_sd")]
heat_rmsesd <- heat_rmsesd[!duplicated(heat_rmsesd),]
# change corine to factors so there are no gaps for missing classes
heat_rmsesd$corine <- as.factor(heat_rmsesd$corine)
heat_rmsesd_cross <- reshape(heat_rmsesd, idvar = "corine", timevar = "month", direction = "wide")
write.csv(heat_rmsesd_cross, paste0(fig_path, "070_heat_rmsesd_cross_", comm_mod, ".csv"))

```

#actual plotting
##observation plots

```{r}
#####
### NDVI and PAI over time #take final aestetics from 116 plotting
#####
plot_pai <- function(dat, plot_comm){
  box_pai <- ggplot(dat, aes(x=as.character(month), y=pai, fill = as.character(corine))) +
    geom_boxplot()+
    
    #ggtitle(paste0("PAI ", plot_comm))+
    theme_bw()+
    xlab("Month")+
    ylab("PAI")+
    # scale_fill_discrete(name = "legend", labels = cor_lab)+
    scale_fill_manual(values = cor_val,
                      labels = cor_lab)+
    scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
                  labels = trans_format("log10", math_format(10^.x)))

  ggsave(filename = paste0(fig_path, "070_box_pai", comm_mod, "_", plot_comm, ".pdf"),
         plot = box_pai,
         width = 200, height = 150, units = "mm", dpi = 300)
  return(box_pai)
}

pai_2021 <- plot_pai(test_data, "2021")
pai_2019 <- plot_pai(train_data[train_data$year == 2019,], "2019")
pai_2020 <- plot_pai(train_data[train_data$year == 2020,], "2020")
pai_19_20_21 <- plot_pai(rbind(st_drop_geometry(train_data), test_data[,!colnames(test_data) %in% c("geometry", "pred") ]), "2019-2021")


plot_ndvi <- function(dat, plot_comm){
  box_ndvi <- ggplot(dat, aes(x=as.character(month), y=NDVI, fill = as.character(corine))) +
    geom_boxplot()+
    #ggtitle(paste0("NDVI ", plot_comm))+
    theme_bw()+
    xlab("Month")+
    ylab("NDVI")+
    # scale_fill_discrete(name = "legend", labels = cor_lab)
   scale_fill_manual(values = cor_val,
                      labels = cor_lab)
  # print(box_ndvi)
  ggsave(filename = paste0(fig_path, "070_box_ndvi", comm_mod, "_", plot_comm, ".pdf"),
         plot = box_ndvi,
         width = 200, height = 150, units = "mm", dpi = 300)
  return(box_ndvi)
}

ndvi_2021 <- plot_ndvi(test_data, "2021")
ndvi_2019 <- plot_ndvi(train_data[train_data$year == 2019,], "2019")
ndvi_2020 <- plot_ndvi(train_data[train_data$year == 2020,], "2020")
ndvi_19_20_21 <- plot_ndvi(rbind(st_drop_geometry(train_data), test_data[,!colnames(test_data) %in% c("geometry", "pred") ]), "2019-2021")

# Combine NDVI and PAI plot

plot_list <- list(pai_19_20_21, ndvi_19_20_21)
plot_grid <-
  ggpubr::ggarrange(
    # plotlist = plot_list, 
    pai_19_20_21 + rremove("xlab") + rremove("x.text") + rremove("x.ticks"), 
    ndvi_19_20_21,
    ncol= 1, nrow = 2, heights = c(0.9, 1),
    common.legend = T, legend = c("bottom", "left"),
    font.label = list(size = 3))

plot(plot_grid)

ggsave(filename = paste0(fig_path, "070_pai_ndvi_dynamic_combi.png"),
       plot = plot_grid,
       width = 200, height = 150, units = "mm", dpi = 300)

ggsave(filename = paste0(fig_path, "070_pai_ndvi_dynamic_combi.pdf"),
       plot = plot_grid,
       width = 200, height = 150, units = "mm", dpi = 300)


```

##modeling plots
```{r}
#####
### heatmap performance
##### 
heaty_r2 <-
  ggplot(data = heat_r2, mapping = aes(x = month, y = corine, fill = Rsquared)) + 
  geom_tile() + 
  geom_text(aes(label = round(Rsquared, 2))) +
  scale_fill_viridis(discrete = F) +
  labs(fill = "R²")+
  xlab(label= "month")+
  theme_bw()+
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())+
  scale_y_discrete(expand=c(0,0), labels = cor_lab)+
  scale_x_discrete(expand=c(0,0))
print(heaty_r2)
ggsave(filename = paste0(fig_path, "070_heaty_r2", comm_mod, ".pdf"),
       plot = heaty_r2,
       width = 200, height = 150, units = "mm", dpi = 300)


heaty_rmsesd <-
  ggplot(data = heat_rmsesd, mapping = aes(x = month, y = corine, fill = RMSE_sd)) + 
  geom_tile() + 
  geom_text(aes(label = round(RMSE_sd, 2))) +
  scale_fill_viridis_c(limits = c(0, 2.5), oob = scales::squish) +
  labs(fill = "RMSE/sd")+
  xlab(label= "month")+
  theme_bw()+
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())+
  scale_y_discrete(expand=c(0,0), labels = cor_lab)+
  scale_x_discrete(expand=c(0,0))
print(heaty_rmsesd)
ggsave(filename = paste0(fig_path, "070_heaty_rmsesd", comm_mod, ".pdf"),
       plot = heaty_rmsesd,
       width = 200, height = 150, units = "mm", dpi = 300)

#####
### Performance across corine
#####
points_corine <- ggplot(errors_corine_long, aes(corine, value))+
  geom_point(aes(colour = factor(error_metric)), size = 5)
print(points_corine)

#####
### Performance over time
#####
points_month <- ggplot(errors_month_long, aes(month, value))+
  geom_point(aes(colour = factor(error_metric)), size = 5)
print(points_month)
ggsave(filename = paste0(fig_path, "070_points_month", comm_mod, ".pdf"),
       plot = points_month,
       width = 200, height = 150, units = "mm", dpi = 300)

#####
### variable importance
#####
df_var <- varImp(model)$importance
colnames(df_var) <- "importance"
df_var$var <- row.names(df_var)
df_var <- df_var[order(df_var$importance),]
df_var$var <- factor(row.names(df_var), levels = df_var$var)
df_var$labels <- c("NIR - Band 08", 
                   "Vegetation red edge - Band 06", 
                   "Narrow NIR - Band 8a", 
                   "Vegetation red edge - Band 07",
                   "Green - Band 03", 
                   "EVI", 
                   "Vegetation red edge - Band 05", 
                   "Blue - Band 02", 
                   "VH", 
                   "VV", 
                   "Red - Band 04")

                   



plot_varImp <- 
ggplot(data = df_var, aes(x = var, y = importance))+
  geom_bar(width = 0.1, stat="identity")+
  coord_flip()+
  theme_bw()+ 
  xlab("predictor") +
  ylab("importance")+
  scale_x_discrete(labels=df_var$labels)+
  scale_y_continuous(expand = c(0,1))
print(plot_varImp)
ggsave(filename = paste0(fig_path, "070_plot_varImp", comm_mod, ".pdf"),
       plot = plot_varImp,
       width = 200, height = 150, units = "mm", dpi = 300)
```

## obs ~ pred

```{r pressure, echo=FALSE}
 ggplot(test_data, aes(pai, pred))+ 
  geom_point()
ggsave(filename = paste0(fig_path, "070_plot_obs_pred", comm_mod, ".pdf"),
       plot = plot_varImp,
       width = 200, height = 150, units = "mm", dpi = 300)
```
